# see grasp_execution/config/SimpleAutomatedGraspTemplate.yaml
# for documentation of parameters.

robot_namespace: jaco
robot_name: jaco
robot_finger_joint_names:
    - jaco_finger_joint_0
    - jaco_finger_joint_2
    - jaco_finger_joint_4



# Pose for the object in the GraspIt! world
# such that it lies on the table (specified in table_filename)
graspit_object_pose:
    x: 0
    y: 250
    z: -500
    qx: 0
    qy: 0
    qz: 0
    qw: 1

pose_above_object: 0.175
x_from_object: 0.0
y_from_object: -0.02
open_angles: 0.05
close_angles: 0.6
effector_pos_tolerance: 0.02
effector_ori_tolerance: 0.1
joint_angle_tolerance: 0.05
plan_tolerance_factor: 0.1
arm_reach_span: 2
planning_group: Arm
joint_states_topic: /jaco/joint_state
grasp_action_name: /jaco/grasp_execution/grasp
joint_trajectory_action_name: /jaco/joint_trajectory_action
request_object_service: /gazebo_objects/get_info
moveit_motion_plan_service: /plan_kinematic_path
moveit_state_validity_service: /check_state_validity
moveit_get_planning_scene_service: /get_planning_scene
moveit_set_planning_scene_topic: /planning_scene
